### ISSUE TITLE
Automatically add RSVP widget for meetups

### ISSUE THREAD

**Issue by attheodo** [skgtech/skgtech.github.io#109]
It'd be great if we could parse the meetup.com event id for a meetup via a tag in the event description and automatically generate RSVP widgets for all meetups on our calendar section.

Ideally we want the RSVP button, right below the time/date div and horizontally aligned in relation to that.

Generate mock widgets here: http://www.meetup.com/meetup_api/buttons/

**Comment by thanpolas** [comment]
@attheodo I did everything meetup.com said and created http://skgtech.io/test.html

I have also added your snippet there and they both do not work... please paste the JS snippet your meetup.com tells your to paste, here's mine:

```html
<script>
    ! function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (!d.getElementById(id)) {
            js = d.createElement(s);
            js.id = id;
            js.async = true;
            js.src = "https://a248.e.akamai.net/secure.meetupstatic.com/s/script/2012676015776998360572/api/mu.btns.js?id=q4omlq8d5deobstsmtepk04t8s";
            fjs.parentNode.insertBefore(js, fjs);
        }
    }(document, "script", "mu-bootjs");
</script>
```

please us http://jsbeautifier.org/ to format the snippet

**Comment by attheodo** [comment]
@thanpolas what error are you getting? #define "do not work"
