### ISSUE TITLE
Fix styling on auxilary links

### ISSUE THREAD

**Issue by attheodo** [skgtech/skgtech.github.io#133]
![image](https://cloud.githubusercontent.com/assets/881195/14580681/e6a637d6-03dd-11e6-9f2b-103e96f86dc9.png)
![image](https://cloud.githubusercontent.com/assets/881195/14580682/ef05487c-03dd-11e6-8773-1ce8971fa136.png)

Only `<a>` should be underlined

**Comment by thanpolas** [comment]
This goes for #communities too
