### ISSUE TITLE
Pending tasks before ui-v3 can be merged to master

### ISSUE THREAD

**Issue by thanpolas** [skgtech/skgtech.github.io#152]
- [x] populate history items
- [x] cross check hero sections on /
- [x] project items in /projects do not have meta-items (i.e presentation material links)
- [x] leipoun ta pages twn together
- [x] confirm oti paizei to newsletter (to slack to testara)
- [x]  update 2016 credits and acknowledgements

**Comment by attheodo** [comment]
Please confirm #160 is fine for pending item no: 2 and let's merge already
