### ISSUE TITLE
Transform Styles to Less

### ISSUE THREAD

**Issue by thanpolas** [skgtech/skgtech.github.io#2]
As we used a ready-made template, the styles where is plain .css format, over time we need to turn them back into .less files...

* Current styles are in [`assets/css/main.css`](https://github.com/skgtech/skgtech.github.io/blob/master/assets/css/main.css)
* The current template uses Bootstrap 3.x so we need to upgrade the [bower package](https://github.com/skgtech/skgtech.github.io/blob/master/.bowerrc)
* The `.less` sources are in the [`assets/styles`](https://github.com/skgtech/skgtech.github.io/tree/master/assets/styles) folder, they are mostly empty files or contain styles from the original template, feel free to remove them when replacing with the new styles.
* A Grunt task is ready for you to build and minify the less files, just run: `grunt css`
* This will output a minified style file at `assets/themes/twitter/css/styles.css`
* Once you are done, [update the master layout file](https://github.com/skgtech/skgtech.github.io/blob/master/_includes/themes/twitter/default.html#L13-L17) and make it point to the newly built .css file.

**Comment by kbariotis** [comment]
Closing this as we moving to brand new site.
