### ISSUE TITLE
Join us on slack.com

### ISSUE THREAD

**Issue by kbariotis** [skgtech/skgtech.github.io#25]
For our top secret, how-to-destroy-the-universe conversations, join us on http://skgtech.slack.com/. Post your email here or ping me on [Twitter](http://twitter.com/kbariotis).

**Comment by kootoopas** [comment]
Hey there. Care to send an invitation to fotis.koutoupas@gmail.com?

**Comment by Navideck-fotis** [comment]
Invite plz!
fdimanidis@gmail.com
--
Fotis Dimanidis, Founder/CEO
NaviDeck - Your daily smart co-driver
www.navideck.com

**Comment by petros** [comment]
amiridis ατ γούγλης mail ντοτ com

**Comment by kbariotis** [comment]
@petros Slack complains that "This person was recently invited. No need to invite them again just yet.". Would you please search your mail for a past invitation?

**Comment by georgiats** [comment]
Me too!
georgia.tsiamanta (@) gmail (.) com

**Comment by attheodo** [comment]
I Just invited him
--
Thanos Theodoridis
Senior iOS Engineer - UX/UI Designer
@attheodo - Skype: theodoridis.thanos

**Comment by hypest** [comment]
stefanostogoulidis@gmail.com please :)

**Comment by ntemposd** [comment]
και εγω θέλω,

ntemposd@gmail.com

On Sun, Jan 18, 2015 at 12:24 PM, Stefanos Togoulidis <
notifications@github.com> wrote:

> stefanostogoulidis@gmail.com please :)
>
> On Sun, Jan 18, 2015 at 11:48 AM, Thanos Theodoridis <
> notifications@github.com> wrote:
>
> > I Just invited him
> > --
> > Thanos Theodoridis
> > Senior iOS Engineer - UX/UI Designer
> > @attheodo - Skype: theodoridis.thanos
> >
> >
> >
> >
> >
> > > On Jan 18, 2015, at 11:47 AM, Kostas Bariotis <
> notifications@github.com>
> > wrote:
> > >
> > > @petros <https://github.com/petros> Slack complains that "This person
> > was recently invited. No need to invite them again just yet.". Would you
> > please search your mail for a past invitation?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub <
> >
> https://github.com/skgtech/skgtech.github.io/issues/25#issuecomment-70402104>.
>
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/skgtech/skgtech.github.io/issues/25#issuecomment-70402125>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skgtech/skgtech.github.io/issues/25#issuecomment-70402955>
> .
>



-- 
*About <http://about.me/ntemposd> | Professional
<https://www.linkedin.com/in/ntemposd>*

*Skype: ntemposd*

**Comment by superdecimal** [comment]
on more pretty please with sugar on top ;p
superdecimal@gmail.com

**Comment by geoah** [comment]
ena invite parakalw sto ajcool99@gmail.com :)
