### ISSUE TITLE
Redirect all non secure traffic to secure

### ISSUE THREAD

**Issue by hsoc** [skgtech/skgtech.github.io#257]
It's 2018. (context: https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html)

**Comment by kbariotis** [comment]
@hsoc its already enabled. We have to redirect all non secure traffic to secure. I believe the certificate is being provided by Cloudflare, so the setting must be there.

**Comment by hsoc** [comment]
done (via cloudflare)
