### ISSUE TITLE
Columns at Index Page

### ISSUE THREAD

**Issue by kbariotis** [skgtech/skgtech.github.io#42]
The calendar sections works with `flex-box` while the communities sections works with `bootstrap` grid. (!?!?!). 

Let's find a similar structure to apply to both. The required solution must work well with equal heights of the columns/boxes, preferentially not with JS.

**Comment by thanpolas** [comment]
@kbariotis is this issue still active?

**Comment by thanpolas** [comment]
@kbariotis ping ping

**Comment by kbariotis** [comment]
Flexbox is still being used here and there without and concrete documentation or API. We could close this and work it on the go.
