### ISSUE TITLE
Fix icons on about page

### ISSUE THREAD

**Issue by thanpolas** [skgtech/skgtech.github.io#57]
* [ ] Find correct icons for the three sections
* [x] Fix styling on the 1st and 3rd section's icons http://than.pol.as/dtpp - should be like http://than.pol.as/dtcL

**Comment by attheodo** [comment]
@geoah sort this out please. :trollface:

**Comment by geoah** [comment]
On it! :P

**Comment by varemenos** [comment]
This seems to be fixed, closing.
