### ISSUE TITLE
Style the contact section on about

### ISSUE THREAD

**Issue by thanpolas** [skgtech/skgtech.github.io#64]
Style the contact section on about http://skgtech.io/about/#contact

**Comment by kbariotis** [comment]
@thanpolas there is no such block at the design. Do we really need it?

**Comment by thanpolas** [comment]
sure, footer works

**Comment by kbariotis** [comment]
let me add a few links like the meetup and an email link

**Comment by kbariotis** [comment]
resolved by #77
